version: 0.2

env:
  variables:
    S3_BUCKET: "{{s3_bucket_url}}"
phases:
  install:
    runtime-versions:
      nodejs: 14
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - npm install
      - npm install -g @angular/cli
  build:
    commands:
      - echo Build started on `date`
      - ng build 

artifacts:
  files:
      - '**/*'
  base-directory: 'dist*'
  discard-paths: yes